x = int(input("Entrez x: "))
y = int(input("Entrez y: "))
print("\nAvant permutation:")
print(f"x : {x}")
print(f"y : {y}")
x = x * y
y = int(x / y)
x = int(x / y)
print("\nAprès permutation:")
print(f"x : {x}")
print(f"y : {y}")